version: '3'
services:
  app:
    image: node:16
    container_name: app
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c 'npm install -g npm@latest && npm install && npm run start'
    ports:
      - "5173:5173"
